### PR TITLE
61 fix cga

### LINKED ISSUE #61: Algorithm for suggesting appropriate captions
- [ ] Fix existing algorithm to our liking

- [ ] Incorporate user provided caption length as a factor to suggest captions

- [ ] Given tags for the image, use Word2Vec to identify similar tags, thus generating more tags for each image, and look for captions wtih these tags

- [ ] Rank eligible captions appropriatelty

### PR DESCRIPTION
**Pull request by prashant616**
# Pull Request

- updated CGA to return mid and long captions
- updated algorithm for long captions
- refactored code to remove duplication
- corner cases when caption has less than 3 or 5 line handled
- corner case when azure returns no tags handled
- image tags from azure now also returned with cation objects

Fixes #61 

### Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [X] My PR follows the style guidelines of this project
- [X] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

File: go/server/handler.go [hunk 1]
```diff
@@ -67,11 +77,19 @@ func getCaption(c *gin.Context) {
...
+		log.Println("azure SDK returned 0 tags for the image")
+		c.String(500, "azure SDK returned 0 tags for the image")
+		return
+	}
 	client := db.ConnectToDB()
 	captions := db.GetCaptionsUsingTags(client, tags)
 	db.CloseConnectionDB(client)
 
-	c.JSON(200, GenerateCaption(&captions, &tags, captionLength))
+	c.JSON(200, gin.H{
```
Comment (prashant616) [inline go/server/handler.go]: @kaustubhhiware this might affect front-end
azure tags is now also returned with captions

File: go/server/handler.go [hunk 2]
```diff
@@ -45,7 +45,12 @@ func (p PairList) Len() int           { return len(p) }
 func (p PairList) Less(i, j int) bool { return p[i].Value < p[j].Value }
 func (p PairList) Swap(i, j int)      { p[i], p[j] = p[j], p[i] }
 
-var computerVisionContext context.Context
+var (
+	computerVisionContext context.Context
+	midCaptionLines =  3
+	longCaptionLines = 5
+	numberOfResultsToReturn = 10
```
Comment (kaustubhhiware) [inline go/server/handler.go]: Great !

File: go/db/db.go [hunk 3]
```diff
@@ -264,7 +264,7 @@ func GetCaptionsUsingTag(client *mongo.Client, tag string) []models.Caption {
 		log.Println("Find ERROR:", err)
 		defer cursor.Close(ctx)
 	} else {
-		log.Println("Find() API result:", cursor)
+		// log.Println("Find() API result:", cursor)
```
Comment (kaustubhhiware) [inline go/db/db.go]: I think it would be a good idea to keep the logs, simply for tracking the results and what API calls have been made, not sure just yet.

Comment (kaustubhhiware) [reply go/db/db.go]: If it's just this function, that's fine I guess¯\_(ツ)_/¯
